### PR TITLE
Remove space after em dash

### PR DESCRIPTION
**Pull request by foolip**
http://www.thepunctuationguide.com/em-dash.html

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@foolip, can you check if you have joined the WICG? https://www.w3.org/community/wicg/participants

**Comment by foolip** [comment]
I've requested to join now, which is not an automatic process.

**Comment by foolip** [comment]
It's done, but the IPR check has to be retriggered somehow.

**Comment by marcoscaceres** [comment]
Yep, will do it tomorrow unless one of the other chairs beats me to it.

**Comment by marcoscaceres** [comment]
@foolip done. Ok, hopefully now fixed throughout the whole WICG org.

**Comment by foolip** [comment]
Thanks! Wanna merge my 1-byte change as well? :)

**Comment by marcoscaceres** [comment]
@foolip, sent you a collaborator link with write access. @beverloo is admin, if you want to add anyone else.

**Pull request merged**
